Search:
	HEADER_CG_STATE_CHECKER						= 206,

Add below:
	HEADER_CG_NM_HB_V1 = 221, // DO NOT CHANGE THIS VALUE, IF IT'S USED BY ANOTHER PACKET HEADER CHABGE IT IN THE OTHER HEADER
	HEADER_CG_NM_HB_V2 = 222, // DO NOT CHANGE THIS VALUE, IF IT'S USED BY ANOTHER PACKET HEADER CHABGE IT IN THE OTHER HEADER

---

Search: (in TPacketCGLogin2)
    DWORD	adwClientKey[4];

Add below:
#if defined(ENABLE_NOMERCY_ANTICHEAT) && defined(ENABLE_NOMERCY_PREMIUM_PLAN)
    char	szNoMercySID[128 + 1];
#endif
